### ISSUE TITLE
Declaração das structs

### ISSUE THREAD

**Issue by FelipeGdM** [ThundeRatz/STM32RF24#1]
Dando uma olhada no código da biblioteca, me surgiu uma dúvida existencial. Por que a struct é declarada com ```__attribute__((packed))``` ?
 https://github.com/ThundeRatz/STM32RF24/blob/10ad73aac27579ba8762adc290820215a771dce0/inc/rf24_platform.h#L39

Confesso que tive que pesquisar na [documentação do gcc](https://gcc.gnu.org/onlinedocs/gcc-3.3/gcc/Type-Attributes.html) pra saber o que isso faz

> This attribute, attached to an enum, struct, or union type definition, specified that the minimum required memory be used to represent the type.

> Specifying this attribute for struct and union types is equivalent to specifying the packed attribute on each of the structure or union members. Specifying the -fshort-enums flag on the line is equivalent to specifying the packed attribute on all enum definitions.

É realmente necessário fazer isso? Estamos economizando alguns poucos bytes nessa brincadeira, mas como não teremos a declaração de muitas variáveis do tipo ```rf24_platform_t```, não vejo uma economia de memória significativa.

Se não for estritamente necessário, acho que é melhor simplificar e tirar esse atributo da declaração

[Is gcc's __attribute__((packed)) / #pragma pack unsafe?](https://stackoverflow.com/questions/8568432/is-gccs-attribute-packed-pragma-pack-unsafe)
[Why you shouldn’t use __attribute__((packed))](http://digitalvampire.org/blog/index.php/2006/07/31/why-you-shouldnt-use-__attribute__packed/)

**Comment by LucasHaug** [comment]
De fato, pra esse caso não precisa usar esse atributo, essa `struct` não tem nenhuma necessidade de alinhamento específico ou de "empacotar" os membros da `struct`.

**Comment by LucasHaug** [comment]
Só por curiosidade, tipo nesse caso [aqui](https://github.com/CombatSim/PPM_Receiver/blob/e167c4e526c3dd7286e56dac9f35018fa45b2e2b/src/joystick.c#L21) era necessário por exemplo usar o `__attribute__((packed))` porque essa `struct` aí é o pacote de dados que nesse caso aí eu vou mandar por USB, então como o pacote não pode ter esse padding bytes, tem que estar tudo juntinho.
